[build]
base = "site"
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.76.4"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"